### ISSUE TITLE
Arbitrary Commands?

### ISSUE THREAD

**Issue by zedaxisllc** [dougbrion/OctoRest#5]
I seem to be having some trouble getting the printer to respond to the .gcode() command. I can see the command show up in the terminal and the printer responds with 'OK' but the command doesn't seem to be executed. Oddly enough, if I copy/paste the text from the terminal window into the input line and send it, the printer responds appropriately. Any idea what might be going on here?

**Comment by dougbrion** [comment]
What gcode command are you sending to the printer?

**Comment by jefflongo** [comment]
Seems to work for me

**Comment by dougbrion** [comment]
Thanks @jefflongo. Works for me too, will close this issue and we can re-open if anyone else has a problem.
