### ISSUE TITLE
Application Keys Plugin workflow support

### ISSUE THREAD

**Issue by TheYarin** [dougbrion/OctoRest#7]
The first thing anyone who wants to use this client will need to do is get an API key.
Currently, the best practice regarding getting an API key is to programmatically request one.

I think it would be very appropriate for this project to include support for this process.

BTW, thank you for this wonderful project!

**Comment by dougbrion** [comment]
Sounds like a great idea - I will look into it!

Feel free to implement the feature if you want and create a pull request. :)

**Comment by TheYarin** [comment]
I'll definitely give that a try if (hopefully when) I end up using the recommended workflow :)

(for now I'll start MVP style by making the user go get an API key for me)
